# Generated by Django 5.0.2 on 2024-03-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistmodel',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='todolistmodel',
            name='updated_date',
            field=models.DateField(auto_now=True, verbose_name='Updated Date'),
        ),
    ]
